export const ADD_TO_CARD = 'PRODUCT/ADD_TO_CARD'
export const OPEN_CARD_POPUP = 'PRODUCT/OPEN_CARD_POPUP'
export const CLOSE_CARD_POPUP = 'PRODUCT/CLOSE_CARD_POPUP'

export const TOGGLE_ALERT = 'GLOBAL/TOGGLE_ALERT'
export const HIDE_ALERT = 'GLOBAL/HIDE_ALERT'

export const FETCH_LATEST_PRODUCTS = 'PRODUCTS/FETCH_LATEST_PRODUCTS'
export const SHAW_LOADER = 'GLOGAL/SHAW_LOADER'
export const HIDE_LOADER = 'GLOBAL/HIDE_LOADER'


export const SHAW_SING_IN = 'GLOBAL/SHAW_SING_IN'
export const HIDE_SING_IN = 'GLOBAL/HIDE_SING_IN'

export const SHAW_SING_UP = 'GLOBAL/SHAW_SING_UP'
export const HIDE_SING_UP = 'GLOBAL/HIDE_SING_UP'

